
services:
  megangine-service:
    image: registry.gitlab.com/doragasu/docker-sgdk:v2.00
    container_name: megangine
    hostname: megangine
    environment:
      SGDK: /sgdk
    volumes:
      - /src/megangine/src/scripts/compile.sh:/m68k/compile.sh:ro
      - /src/megangine/src/scripts/update-gfx.sh:/m68k/update-gfx.sh:ro
      - /src/megangine/src/src:/m68k/src
      - /src/megangine/src/res:/m68k/res
      - /src/megangine/out:/m68k/out
    entrypoint: ['/bin/bash']
    stdin_open: true  # <--- Mantiene el canal de entrada abierto
    tty: true         # <--- Simula una terminal abierta de fondo
    restart: no
